version: '3.8'

networks:
  kong-net:
    driver: bridge

volumes:
  kong-data:
    driver: local
  postgres-data:
    driver: local

services:
  # Database for Kong
  kong-database:
    image: postgres:13-alpine
    container_name: kong-database
    restart: unless-stopped
    networks:
      - kong-net
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Kong database migration
  kong-migration:
    image: kong:2.8-alpine
    container_name: kong-migration
    command: "kong migrations bootstrap"
    restart: on-failure
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong_password
      KONG_PG_DATABASE: kong
    depends_on:
      - kong-database

  # Kong API Gateway
  kong:
    image: kong:2.8-alpine
    container_name: kong
    restart: unless-stopped
    networks:
      - kong-net
    volumes:
      - ./config:/usr/local/kong/declarative
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong_password
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
    ports:
      - "8000:8000"  # Kong proxy port
      - "8443:8443"  # Kong proxy SSL port
      - "8001:8001"  # Kong admin API port
      - "8444:8444"  # Kong admin API SSL port
    depends_on:
      - kong-database
      - kong-migration
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Kong Manager UI
  kong-manager:
    image: pantsel/konga:latest
    container_name: kong-manager
    restart: unless-stopped
    networks:
      - kong-net
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_PORT: 5432
      DB_USER: kong
      DB_PASSWORD: kong_password
      DB_DATABASE: konga
      NODE_ENV: development
      KONGA_HOOK_TIMEOUT: 120000
      KONGA_LOG_LEVEL: debug
    ports:
      - "1337:1337"
    depends_on:
      - kong-database
      - kong

  # Mock service for testing
  mock-service:
    image: mockserver/mockserver:latest
    container_name: mock-service
    networks:
      - kong-net
    environment:
      MOCKSERVER_SERVER_PORT: 1080
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/mockserver-config.json
    volumes:
      - ./mock-service:/config
    ports:
      - "1080:1080"