apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: avatar-chat-routing
  namespace: istio-system
spec:
  hosts:
    - "api.avatar-chat.com" # External domain
  gateways:
    - avatar-chat-gateway
  http:
    - name: "nvidia-omniverse-avatar"
      match:
        - uri:
            prefix: /v1/avatar/
      route:
        - destination:
            host: nvidia-proxy-service.default.svc.cluster.local
            port:
              number: 80
      timeout: 30s
      retries:
        attempts: 3
        perTryTimeout: 10s
        retryOn: "connect-failure,refused-stream,503"
      headers:
        request:
          add:
            X-API-Version: "v1"

    - name: "nvidia-riva-speech"
      match:
        - uri:
            prefix: /v1/speech/
      route:
        - destination:
            host: nvidia-proxy-service.default.svc.cluster.local
            port:
              number: 80
      timeout: 15s
      retries:
        attempts: 3
        perTryTimeout: 5s
        retryOn: "connect-failure,refused-stream,503"
      headers:
        request:
          add:
            X-API-Version: "v1"

    - name: "nvidia-merlin-conversation"
      match:
        - uri:
            prefix: /v1/conversation/
      route:
        - destination:
            host: nvidia-proxy-service.default.svc.cluster.local
            port:
              number: 80
      timeout: 20s
      retries:
        attempts: 3
        perTryTimeout: 7s
        retryOn: "connect-failure,refused-stream,503"
      headers:
        request:
          add:
            X-API-Version: "v1"

    - name: "avatar-chat-session"
      match:
        - uri:
            prefix: /v1/avatar-chat/
      route:
        - destination:
            host: avatar-chat-session-manager.default.svc.cluster.local
            port:
              number: 8080
      corsPolicy:
        allowOrigins:
          - exact: "https://your-frontend-domain.com"
        allowMethods:
          - POST
          - GET
          - OPTIONS
        allowHeaders:
          - "Content-Type"
          - "Authorization"
        allowCredentials: true