apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: avatar-chat-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: avatar-chat-tls-cert
      hosts:
        - "api.avatar-chat.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: nvidia-proxy-service-dr
  namespace: default
spec:
  host: nvidia-proxy-service.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 1000
        maxRequestsPerConnection: 10
    outlierDetection:
      consecutiveErrors: 5
      interval: 1m
      baseEjectionTime: 5m
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: avatar-chat-session-manager-dr
  namespace: default
spec:
  host: avatar-chat-session-manager.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    outlierDetection:
      consecutiveErrors: 3
      interval: 30s
      baseEjectionTime: 1m
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: default
spec:
  mtls:
    mode: STRICT