# /config/performance/optimization-config.yaml
# Centralized configuration for performance optimization settings.
# This file controls feature flags, performance budgets, and thresholds for various services.

# Caching Service Configuration
caching:
  enabled: true
  default_ttl_seconds: 3600 # 1 hour
  user_profile_ttl_seconds: 7200 # 2 hours
  static_asset_ttl_seconds: 86400 # 24 hours
  feature_flags:
    # A/B test different caching strategies
    ab_test_caching_strategy:
      enabled: true
      traffic_percentage: 10 # 10% of traffic gets the experimental strategy

# CDN Optimization Configuration
cdn:
  enabled: true
  # Adaptive bitrate streaming settings for WebRTC/avatar streaming
  adaptive_bitrate:
    enabled: true
    default_bitrate_kbps: 2000 # Default for unknown network conditions
    bitrate_levels_kbps: [400, 750, 2000, 4000] # Available quality levels
  # Lazy loading settings
  lazy_loading:
    images: true
    videos: true
    # Load assets within 1.5x of the viewport
    intersection_observer_margin: "200px"

# Database Optimization Configuration
database:
  connection_pooling:
    enabled: true
    max_connections: 50
    idle_timeout_millis: 30000
  query_optimization:
    slow_query_threshold_ms: 150
    # Flag to enable/disable detailed query analysis in non-production environments
    enable_query_analysis: true

# Memory Management Configuration
memory_management:
  enabled: true
  monitoring_interval_ms: 60000 # 1 minute
  # Threshold for triggering high memory usage alerts
  heap_usage_alert_threshold: 0.8 # 80% of heap limit
  object_pooling:
    avatar_rendering: true
    conversation_state: true

# Asset Compression Configuration
compression:
  enabled: true
  # On-the-fly compression for dynamic API responses
  dynamic_compression:
    enabled: true
    brotli_enabled: true # Prefer Brotli over Gzip when available
  # Image optimization settings
  image_optimization:
    enabled: true
    default_quality: 85 # Default WebP/JPEG quality
    # Progressive enhancement: serve lower quality initially, then higher
    progressive_loading: true

# Performance Budgets and SLA Monitoring
performance_budgets:
  # Service Level Agreement (SLA) targets
  sla:
    p95_response_time_ms: 200 # 95th percentile of requests should be < 200ms
    p99_response_time_ms: 500 # 99th percentile < 500ms
    error_rate_percentage: 0.1 # Less than 0.1% error rate
  # Budgets for specific page types or assets
  budgets:
    - path: "/avatar/chat"
      max_js_size_kb: 250
      max_image_size_kb: 500
      max_render_time_ms: 1500
    - path: "/assets/avatars/*"
      max_asset_size_kb: 2048 # 2MB limit for avatar models

# WebRTC Optimization for Avatar Streaming
webrtc:
  enabled: true
  stun_turn_servers:
    - urls: "stun:stun.l.google.com:19302"
    - urls: "turn:user@your-turn-server.com"
      username: "user"
      credential: "password"
  # Codec preferences for balancing quality and performance
  codec_preference:
    video: ["VP9", "AV1", "H264"] # Prefer modern codecs
    audio: ["Opus", "AAC"]

# Graceful Degradation Strategies
graceful_degradation:
  # If a service fails, what is the fallback behavior?
  service_failure_mode:
    # e.g., if avatar rendering fails, show a static 2D image
    avatar_rendering: "static_image"
    # e.g., if recommendation engine fails, show popular products
    recommendations: "show_popular"