# Docker deployment configuration for the WooCommerce Avatar Chat Plugin.
# This file is intended for use with Docker Compose for local development
# and testing of the WordPress environment with the plugin installed.

version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8081:80" # Expose WordPress on port 8081
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./../../integrations/woocommerce:/var/www/html/wp-content/plugins/ai-avatar-chat-woocommerce
      - ./../../apps/woocommerce:/var/www/html/wp-content/themes/storefront-child # Example theme
    depends_on:
      - db
    networks:
      - wpsite

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wpsite

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - wpsite

networks:
  wpsite:

volumes:
  db_data:

# Deployment Guide:
# 1. Place this file in the `deploy/platform-configs` directory.
# 2. From this directory, run `docker-compose up -d`.
# 3. Access the WordPress site at http://localhost:8081.
# 4. Complete the WordPress installation.
# 5. Go to the Plugins section and activate the "AI Avatar Chat for WooCommerce" plugin.
# 6. Ensure WooCommerce is installed and configured.
# 7. The `integrations/woocommerce` directory is mounted as a volume, so changes
#    to the plugin code will be reflected in the running container.