# Dependabot configuration file
# Optimized to prevent commit spam by grouping dependencies and limiting PRs
# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Python dependencies in root directory
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    groups:
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "*dev*"
          - "*test*"
      development-dependencies:
        patterns:
          - "*dev*"
          - "*test*"
    labels:
      - "dependencies"
      - "python"

  # JavaScript dependencies - Apps directory
  - package-ecosystem: "npm"
    directory: "/apps"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    groups:
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "*dev*"
          - "*test*"
          - "@types/*"
      development-dependencies:
        patterns:
          - "*dev*"
          - "*test*"
          - "@types/*"
    labels:
      - "dependencies"
      - "javascript"
      - "apps"

  # JavaScript dependencies - Services directory
  - package-ecosystem: "npm"
    directory: "/services"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    groups:
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "*dev*"
          - "*test*"
          - "@types/*"
      development-dependencies:
        patterns:
          - "*dev*"
          - "*test*"
          - "@types/*"
    labels:
      - "dependencies"
      - "javascript"
      - "services"

  # JavaScript dependencies - Tests directory
  - package-ecosystem: "npm"
    directory: "/tests"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    groups:
      test-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "javascript"
      - "testing"

  # JavaScript dependencies - Website directory
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    groups:
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "*dev*"
          - "*test*"
          - "@types/*"
      development-dependencies:
        patterns:
          - "*dev*"
          - "*test*"
          - "@types/*"
    labels:
      - "dependencies"
      - "javascript"
      - "website"

  # JavaScript dependencies - Root directory (legacy support)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    groups:
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "*dev*"
          - "*test*"
          - "@types/*"
      development-dependencies:
        patterns:
          - "*dev*"
          - "*test*"
          - "@types/*"
    labels:
      - "dependencies"
      - "javascript"
      - "root"