# Dependabot configuration file
# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Python dependencies in root directory
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"

  # JavaScript dependencies in root directory
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "javascript"

  # JavaScript dependencies in frontend directory
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "javascript"
      - "frontend"

  # JavaScript dependencies in auth directory
  - package-ecosystem: "npm"
    directory: "/auth"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "javascript"
      - "auth"

  # JavaScript dependencies in src/sdk/opticians-catalog directory
  - package-ecosystem: "npm"
    directory: "/src/sdk/opticians-catalog"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "javascript"
      - "sdk"

  # JavaScript dependencies in tests/e2e directory
  - package-ecosystem: "npm"
    directory: "/tests/e2e"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "javascript"
      - "testing"

  # JavaScript dependencies in tests/integration directory
  - package-ecosystem: "npm"
    directory: "/tests/integration"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "javascript"
      - "testing"

  # JavaScript dependencies in src/varai/vertex_ai_integration directory
  - package-ecosystem: "npm"
    directory: "/src/varai/vertex_ai_integration"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "javascript"
      - "varai"

  # JavaScript dependencies in src/webhook directory
  - package-ecosystem: "npm"
    directory: "/src/webhook"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "javascript"
      - "webhook"