steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile.staging', '-t', 'gcr.io/ml-datadriven-recos/varai-admin-staging:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ml-datadriven-recos/varai-admin-staging:latest']
images:
- 'gcr.io/ml-datadriven-recos/varai-admin-staging:latest'