_format_version: "2.1"
_transform: true

services:
  # Product Service
  - name: product-service
    url: http://mock-service:1080/products
    routes:
      - name: product-routes
        paths:
          - /api/v1/products
        strip_path: false
        protocols:
          - http
          - https
    plugins:
      - name: rate-limiting
        config:
          minute: 60
          policy: local
      - name: cors
        config:
          origins:
            - '*'
          methods:
            - GET
            - POST
            - PUT
            - DELETE
          headers:
            - Content-Type
            - Authorization
          exposed_headers:
            - X-Auth-Token
          credentials: true
          max_age: 3600

  # User Service
  - name: user-service
    url: http://mock-service:1080/users
    routes:
      - name: user-routes
        paths:
          - /api/v1/users
        strip_path: false
        protocols:
          - http
          - https
    plugins:
      - name: rate-limiting
        config:
          minute: 30
          policy: local
      - name: cors
        config:
          origins:
            - '*'
          methods:
            - GET
            - POST
            - PUT
            - DELETE
          headers:
            - Content-Type
            - Authorization
          exposed_headers:
            - X-Auth-Token
          credentials: true
          max_age: 3600

  # Authentication Service
  - name: auth-service
    url: http://mock-service:1080/auth
    routes:
      - name: auth-routes
        paths:
          - /api/v1/auth
        strip_path: false
        protocols:
          - http
          - https
    plugins:
      - name: rate-limiting
        config:
          minute: 20
          policy: local
      - name: cors
        config:
          origins:
            - '*'
          methods:
            - POST
          headers:
            - Content-Type
          exposed_headers:
            - X-Auth-Token
          credentials: true
          max_age: 3600

  # Client Portal API Service
  - name: client-portal-service
    url: http://client-portal-api:8000
    routes:
      - name: client-portal-routes
        paths:
          - /api/client-portal
        strip_path: true
        protocols:
          - http
          - https
    plugins:
      - name: rate-limiting
        config:
          minute: 60
          policy: local
      - name: cors
        config:
          origins:
            - '*'
          methods:
            - GET
            - POST
            - PUT
            - DELETE
          headers:
            - Content-Type
            - Authorization
          exposed_headers:
            - X-Auth-Token
          credentials: true
          max_age: 3600
      - name: key-auth
        config:
          key_names:
            - apikey
          hide_credentials: true

# Global plugins
plugins:
  - name: request-termination
    config:
      status_code: 503
      message: "API Gateway is currently in maintenance mode"
    enabled: false
  
  - name: prometheus
    config:
      status_codes: true
      latency: true
      bandwidth: true
      upstream_health: true
    
  - name: request-id
    config:
      header_name: X-Request-ID
      generator: uuid

# Consumers
consumers:
  - username: api-client
    custom_id: client-001
    keyauth_credentials:
      - key: demo-api-key

  - username: client-portal
    custom_id: client-portal-001
    keyauth_credentials:
      - key: client-portal-api-key

# Upstreams for load balancing
upstreams:
  - name: product-service-upstream
    targets:
      - target: mock-service:1080
        weight: 100
    healthchecks:
      active:
        http_path: /health
        healthy:
          interval: 5
          successes: 1
        unhealthy:
          interval: 5
          http_failures: 2

  - name: client-portal-upstream
    targets:
      - target: client-portal-api:8000
        weight: 100
    healthchecks:
      active:
        http_path: /health
        healthy:
          interval: 5
          successes: 1
        unhealthy:
          interval: 5
          http_failures: 2