global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "sku-genie-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["sku-genie-api:8000"]

  - job_name: "sku-genie-scheduler"
    metrics_path: /metrics
    static_configs:
      - targets: ["sku-genie-scheduler:8001"]

  - job_name: "sku-genie-worker"
    metrics_path: /metrics
    static_configs:
      - targets: ["sku-genie-worker:8002"]

  - job_name: "mongodb"
    static_configs:
      - targets: ["mongodb-exporter:9216"]