name: staging
url: https://api-staging.varai.ai
protection_rules:
  required_reviewers: []
  wait_timer: 0
  prevent_self_review: false
deployment_branch_policy:
  protected_branches: false
  custom_branch_policies: true
  custom_branches:
    - main
    - develop