# Development Environment Configuration
environment: dev
project_id: ml-datadriven-recos
region: us-central1
registry: gcr.io/ml-datadriven-recos

# Service configurations
services:
  auth-service:
    image: auth-service
    memory: 512Mi
    cpu: 0.5
    min_instances: 1
    max_instances: 3
    concurrency: 50
    env_vars:
      NODE_ENV: development
      LOG_LEVEL: debug
      
  frontend:
    image: frontend
    memory: 256Mi
    cpu: 0.25
    min_instances: 1
    max_instances: 2
    concurrency: 100
    env_vars:
      NODE_ENV: development
      
  api-gateway:
    image: api-gateway
    memory: 1Gi
    cpu: 1
    min_instances: 1
    max_instances: 5
    concurrency: 80
    env_vars:
      NODE_ENV: development
      LOG_LEVEL: debug

# Database configuration
database:
  connection_pool_size: 5
  
# Monitoring
monitoring:
  enabled: true
  log_level: debug
  
# Security
security:
  allow_unauthenticated: true
  cors_origins: "*"
  
# Blue-green deployment
blue_green:
  enabled: false