# Staging Environment Configuration
environment: staging
project_id: ml-datadriven-recos
region: us-central1
registry: gcr.io/ml-datadriven-recos

# Service configurations
services:
  auth-service:
    image: auth-service
    memory: 1Gi
    cpu: 1
    min_instances: 2
    max_instances: 5
    concurrency: 80
    env_vars:
      NODE_ENV: staging
      LOG_LEVEL: info
      
  frontend:
    image: frontend
    memory: 512Mi
    cpu: 0.5
    min_instances: 2
    max_instances: 4
    concurrency: 100
    env_vars:
      NODE_ENV: staging
      
  api-gateway:
    image: api-gateway
    memory: 2Gi
    cpu: 2
    min_instances: 2
    max_instances: 8
    concurrency: 100
    env_vars:
      NODE_ENV: staging
      LOG_LEVEL: info

# Database configuration
database:
  connection_pool_size: 10
  
# Monitoring
monitoring:
  enabled: true
  log_level: info
  alerts_enabled: true
  
# Security
security:
  allow_unauthenticated: false
  cors_origins: "https://staging.eyewearml.com"
  
# Blue-green deployment
blue_green:
  enabled: true
  health_check_timeout: 300
  rollback_threshold: 5