version: '3.8'

networks:
  auth-net:
    driver: bridge
  api-gateway-net:
    external: true

volumes:
  postgres-data:
    driver: local
  keycloak-data:
    driver: local

services:
  # Database for Keycloak
  postgres:
    image: postgres:13-alpine
    container_name: auth-postgres
    restart: unless-stopped
    networks:
      - auth-net
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_password
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Keycloak Identity and Access Management
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    container_name: auth-keycloak
    restart: unless-stopped
    networks:
      - auth-net
      - api-gateway-net
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./keycloak/themes:/opt/keycloak/themes
      - ./keycloak/extensions:/opt/keycloak/providers
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_password
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_RELATIVE_PATH: /auth
      KC_PROXY: edge
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: 
      - start-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Custom Integration Service
  integration-service:
    build:
      context: ./integration
      dockerfile: Dockerfile
    container_name: auth-integration
    restart: unless-stopped
    networks:
      - auth-net
      - api-gateway-net
    environment:
      KEYCLOAK_URL: http://keycloak:8080/auth
      KEYCLOAK_REALM: varai
      KEYCLOAK_CLIENT_ID: integration-service
      KEYCLOAK_CLIENT_SECRET: integration-service-secret
      API_GATEWAY_URL: http://kong:8000
    ports:
      - "8081:8081"
    depends_on:
      - keycloak
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Admin UI for Authentication Service
  admin-ui:
    build:
      context: ./admin-ui
      dockerfile: Dockerfile
    container_name: auth-admin-ui
    restart: unless-stopped
    networks:
      - auth-net
      - api-gateway-net
    environment:
      KEYCLOAK_URL: http://keycloak:8080/auth
      KEYCLOAK_REALM: varai
      KEYCLOAK_CLIENT_ID: admin-ui
      INTEGRATION_SERVICE_URL: http://integration-service:8081
    ports:
      - "8082:80"
    depends_on:
      - keycloak
      - integration-service