# ==============================================================================
# Production Launch Configuration for AI Avatar Chat System
#
# This file contains all configuration settings for the production launch,
# including feature flags for gradual rollout, service endpoints, and
# deployment strategy parameters.
#
# Version: 1.0.0
# Author: AI-Engineer
# ==============================================================================

# --- Deployment Strategy ---
# Defines the overall strategy for the production launch.
deployment:
  strategy: "blue-green" # Options: "blue-green", "canary", "rolling-update"
  zero_downtime: true
  # Parameters for the deployment orchestrator
  orchestrator:
    timeout_minutes: 60
    failure_threshold_percent: 5

# --- Feature Flags ---
# Allows for the gradual rollout of new features.
# Toggling these flags does not require a new deployment.
feature_flags:
  # Main switch for the entire AI Avatar Chat System
  enable_avatar_chat_system: true

  # Controls the visibility of the avatar on different platforms
  avatar_visibility:
    shopify: 100 # Percentage of users (0-100)
    woocommerce: 50  # Gradual rollout on WooCommerce
    magento: 10      # Canary release on Magento
    html_store: 100

  # Enables advanced AI capabilities
  enable_advanced_personalization: true
  enable_conversation_learning: false # Disabled for initial launch, to be enabled post-launch

  # Controls specific UI features
  enable_facial_animation_smoothing: true
  enable_avatar_customization: false # Phase 2 feature

# --- Service Endpoints ---
# External and internal endpoints for production services.
# Note: Use environment variables for sensitive parts of URLs in a real system.
services:
  # NVIDIA AI Services
  nvidia:
    omniverse_avatar_service: "https://api.nvidia.com/omniverse/avatar"
    riva_speech_service: "https://api.nvidia.com/riva/speech"
    merlin_conversation_service: "https://api.nvidia.com/merlin/conversation"

  # Internal Core Services
  avatar_manager: "http://avatar-manager.prod.internal:8080"
  multi_modal_interface: "http://mmi.prod.internal:8080"

  # Analytics and Monitoring
  analytics_service: "https://analytics.our-domain.com/track"
  monitoring_dashboard: "https://grafana.our-domain.com"

# --- Monitoring & Alerting ---
monitoring:
  # Key performance indicators (KPIs) and their alert thresholds
  kpi_thresholds:
    # Latency for AI responses (in milliseconds)
    p95_response_latency_ms:
      warning: 500
      critical: 1000
    # Error rate for core services
    core_service_error_rate_percent:
      warning: 1
      critical: 3
    # User session success rate
    session_success_rate_percent:
      warning: 99
      critical: 95

  # Alerting configuration
  alerting:
    # Target for critical alerts (e.g., PagerDuty, OpsGenie)
    critical_alert_target: "pagerduty-prod-channel"
    # Target for warning alerts (e.g., Slack)
    warning_alert_target: "slack-channel-#prod-alerts"

# --- Security & Compliance ---
security:
  # Minimum required TLS version for external communication
  minimum_tls_version: "1.2"
  # List of enabled security headers for web responses
  enabled_security_headers:
    - "Strict-Transport-Security"
    - "Content-Security-Policy"
    - "X-Content-Type-Options"
    - "X-Frame-Options"