# Google Cloud Project Configuration for EyewearML Conversational AI

# Project Configuration
project:
  name: eyewearml-conversational-ai
  display_name: "EyewearML Conversational AI"
  organization_id: "ORGANIZATION_ID_TO_BE_REPLACED"  # Replace with actual GCP organization ID
  folder_id: "FOLDER_ID_TO_BE_REPLACED"              # Replace with actual GCP folder ID if applicable
  billing_account: "BILLING_ACCOUNT_TO_BE_REPLACED"  # Replace with actual billing account ID
  
# Project Settings
settings:
  region: us-central1                      # Primary region for deployment
  secondary_regions:                       # Optional secondary regions for redundancy
    - us-east1
    - europe-west1
  default_language: en                     # Default language for the conversational AI
  additional_languages:                    # Additional languages to support
    - fr
    - es
    - de
  
# Required Google APIs
apis:
  - name: dialogflow.googleapis.com        # Dialogflow CX API
    display_name: "Dialogflow API"
    reason: "Core conversational AI functionality"
  
  - name: language.googleapis.com          # Natural Language API
    display_name: "Natural Language API"
    reason: "Enhanced entity recognition and sentiment analysis"
  
  - name: cloudfunctions.googleapis.com    # Cloud Functions API
    display_name: "Cloud Functions API"
    reason: "Webhook implementation for Dialogflow fulfillment"
  
  - name: run.googleapis.com               # Cloud Run API
    display_name: "Cloud Run API"
    reason: "Alternative webhook hosting for more complex scenarios"
  
  - name: storage.googleapis.com           # Cloud Storage API
    display_name: "Cloud Storage API"
    reason: "Storage for conversation assets and exported configs"
  
  - name: logging.googleapis.com           # Cloud Logging API
    display_name: "Cloud Logging API"
    reason: "Centralized logging for the conversational AI system"
  
  - name: monitoring.googleapis.com        # Cloud Monitoring API
    display_name: "Cloud Monitoring API"
    reason: "Monitoring and alerting for the conversational AI system"
  
  - name: firestore.googleapis.com         # Firestore API
    display_name: "Firestore API"
    reason: "Database for conversation context and user profiles"

# Resource Labels
labels:
  environment: development
  application: conversational-ai
  business-unit: customer-experience
  cost-center: digital-transformation

# Additional Settings
additional_settings:
  vpc_network: "NETWORK_NAME_TO_BE_REPLACED"  # Replace with actual VPC network name if applicable
  private_connection: false                  # Whether to use private Google access
  audit_logging:                             # Audit logging configuration
    enabled: true
    log_types:
      - DATA_READ
      - DATA_WRITE
      - ADMIN_READ
  
# Compliance and Security
compliance:
  data_residency: US                        # Data residency requirements
  pii_handling:                            # Personally Identifiable Information handling
    strategy: encryption                   # How to handle PII (encryption, anonymization, etc.)
    data_types:                            # Types of PII this project may handle
      - customer_name
      - email
  security_controls:                        # Additional security controls
    ip_restrictions: false                  # Whether to restrict access by IP
    cloud_armor: false                      # Whether to use Cloud Armor for protection
    cmek: false                             # Whether to use Customer-Managed Encryption Keys
