# Service Accounts Configuration for EyewearML Conversational AI

# Development Environment Service Account
development:
  name: conversational-ai-dev
  display_name: "Conversational AI Development Service Account"
  description: "Service account for development environment of the Conversational AI system"
  roles:
    - role: roles/dialogflow.admin
      reason: "Manage Dialogflow agents and resources in development"
    - role: roles/cloudfunctions.developer
      reason: "Deploy and manage Cloud Functions for webhooks"
    - role: roles/storage.objectAdmin
      reason: "Manage storage objects for conversation assets"
    - role: roles/logging.logWriter
      reason: "Write logs for development activities"
    - role: roles/monitoring.metricWriter
      reason: "Write monitoring metrics"
    - role: roles/datastore.user
      reason: "Access Firestore for conversation data"

# Testing Environment Service Account
testing:
  name: conversational-ai-test
  display_name: "Conversational AI Testing Service Account"
  description: "Service account for testing environment of the Conversational AI system"
  roles:
    - role: roles/dialogflow.client
      reason: "Access Dialogflow for integration testing"
    - role: roles/cloudfunctions.invoker
      reason: "Invoke Cloud Functions during testing"
    - role: roles/storage.objectViewer
      reason: "Read access to storage for testing"
    - role: roles/logging.logWriter
      reason: "Write logs during testing"
    - role: roles/monitoring.metricWriter
      reason: "Write monitoring metrics during testing"
    - role: roles/datastore.user
      reason: "Access Firestore for test data"

# Production Environment Service Account
production:
  name: conversational-ai-prod
  display_name: "Conversational AI Production Service Account"
  description: "Service account for production environment of the Conversational AI system"
  roles:
    - role: roles/dialogflow.client
      reason: "Access Dialogflow in production"
    - role: roles/cloudfunctions.invoker
      reason: "Invoke Cloud Functions in production"
    - role: roles/storage.objectViewer
      reason: "Read access to storage in production"
    - role: roles/logging.logWriter
      reason: "Write logs in production"
    - role: roles/monitoring.metricWriter
      reason: "Write monitoring metrics in production"
    - role: roles/datastore.user
      reason: "Access Firestore for production data"

# CI/CD Service Account
cicd:
  name: conversational-ai-cicd
  display_name: "Conversational AI CI/CD Service Account"
  description: "Service account for CI/CD pipelines of the Conversational AI system"
  roles:
    - role: roles/dialogflow.admin
      reason: "Manage Dialogflow agents and resources during deployment"
    - role: roles/cloudfunctions.developer
      reason: "Deploy Cloud Functions during CI/CD"
    - role: roles/storage.objectAdmin
      reason: "Manage storage objects during deployment"
    - role: roles/iam.serviceAccountUser
      reason: "Use service accounts during deployment"
    - role: roles/run.admin
      reason: "Manage Cloud Run services during deployment"

# Analytics Service Account
analytics:
  name: conversational-ai-analytics
  display_name: "Conversational AI Analytics Service Account"
  description: "Service account for analytics processing of Conversational AI data"
  roles:
    - role: roles/bigquery.dataViewer
      reason: "Access BigQuery for analytics data"
    - role: roles/bigquery.jobUser
      reason: "Run BigQuery jobs for analytics"
    - role: roles/logging.viewer
      reason: "View logs for analytics"
    - role: roles/dialogflow.reader
      reason: "Read Dialogflow data for analytics"

# Access Control Settings
access_control:
  principle: "least-privilege"
  rotation_policy: "every-90-days"
  key_usage:
    development: "local-development-only"
    cicd: "automated-pipelines-only"
    production: "service-to-service-only"
