global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'production'
    project: 'ai-discovery'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # AI Discovery Services
  - job_name: 'ai-discovery-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ai-discovery-service:8080']
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'face-analysis-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['face-analysis-service:8080']
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'recommendation-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['recommendation-service:8080']
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'analytics-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['analytics-service:8080']
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'api-gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-gateway:80']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Google Cloud Monitoring
  - job_name: 'gcp-monitoring'
    gce_sd_configs:
      - project: 'ml-datadriven-recos'
        zone: 'us-central1-a'
        port: 9090
    relabel_configs:
      - source_labels: [__meta_gce_label_environment]
        target_label: environment
      - source_labels: [__meta_gce_label_service]
        target_label: service

  # Cloud Run services discovery
  - job_name: 'cloud-run-services'
    http_sd_configs:
      - url: 'http://service-discovery:8080/cloud-run/services'
        refresh_interval: 60s
    relabel_configs:
      - source_labels: [__meta_cloud_run_service_name]
        target_label: service
      - source_labels: [__meta_cloud_run_revision_name]
        target_label: revision
      - source_labels: [__meta_cloud_run_region]
        target_label: region

  # Widget CDN monitoring
  - job_name: 'cdn-monitoring'
    static_configs:
      - targets: ['cdn.varai.ai']
    metrics_path: '/health'
    scheme: https
    scrape_interval: 60s

  # Platform-specific widget monitoring
  - job_name: 'shopify-widgets'
    http_sd_configs:
      - url: 'http://widget-monitor:8080/shopify/instances'
        refresh_interval: 300s
    metrics_path: '/widget/metrics'
    scheme: https

  - job_name: 'magento-widgets'
    http_sd_configs:
      - url: 'http://widget-monitor:8080/magento/instances'
        refresh_interval: 300s
    metrics_path: '/widget/metrics'
    scheme: https

  - job_name: 'woocommerce-widgets'
    http_sd_configs:
      - url: 'http://widget-monitor:8080/woocommerce/instances'
        refresh_interval: 300s
    metrics_path: '/widget/metrics'
    scheme: https

  - job_name: 'html-widgets'
    http_sd_configs:
      - url: 'http://widget-monitor:8080/html/instances'
        refresh_interval: 300s
    metrics_path: '/widget/metrics'
    scheme: https

# Recording rules for performance optimization
recording_rules:
  - name: ai_discovery_performance
    rules:
      - record: ai_discovery:request_rate_5m
        expr: rate(http_requests_total{job="ai-discovery-service"}[5m])
      
      - record: ai_discovery:error_rate_5m
        expr: rate(http_requests_total{job="ai-discovery-service",status=~"5.."}[5m]) / rate(http_requests_total{job="ai-discovery-service"}[5m])
      
      - record: ai_discovery:response_time_p95_5m
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="ai-discovery-service"}[5m]))

  - name: face_analysis_performance
    rules:
      - record: face_analysis:processing_time_p95_5m
        expr: histogram_quantile(0.95, rate(face_analysis_duration_seconds_bucket[5m]))
      
      - record: face_analysis:success_rate_5m
        expr: rate(face_analysis_total{status="success"}[5m]) / rate(face_analysis_total[5m])

  - name: recommendation_performance
    rules:
      - record: recommendation:generation_time_p95_5m
        expr: histogram_quantile(0.95, rate(recommendation_generation_duration_seconds_bucket[5m]))
      
      - record: recommendation:relevance_score_avg_5m
        expr: avg_over_time(recommendation_relevance_score[5m])

  - name: widget_performance
    rules:
      - record: widget:load_time_p95_5m
        expr: histogram_quantile(0.95, rate(widget_load_duration_seconds_bucket[5m]))
      
      - record: widget:interaction_rate_5m
        expr: rate(widget_interactions_total[5m])
      
      - record: widget:conversion_rate_1h
        expr: rate(widget_conversions_total[1h]) / rate(widget_sessions_total[1h])