# Live Demo Configuration for AI Avatar Chat System
# This configuration enables real NVIDIA API services for live demonstrations

demo:
  name: "AI Avatar Chat System - Live Demo"
  version: "1.0.0"
  description: "Live demonstration using real NVIDIA API services"
  environment: "live-demo"
  
server:
  host: "${DEMO_SERVER_HOST}"
  port: "${DEMO_SERVER_PORT}"
  ssl_enabled: "${DEMO_SSL_ENABLED}"
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "https://demo.commerce-studio.com"

# NVIDIA API Services Configuration
nvidia_services:
  # Reference to external NVIDIA API configuration
  config_file: "config/nvidia/live-api-configuration.yaml"
  
  # Service endpoints (from environment variables)
  omniverse_avatar:
    enabled: true
    endpoint: "${NVIDIA_OMNIVERSE_ENDPOINT}"
    api_key: "${NVIDIA_OMNIVERSE_API_KEY}"
    
  riva_speech:
    enabled: true
    endpoint: "${NVIDIA_RIVA_ENDPOINT}"
    api_key: "${NVIDIA_RIVA_API_KEY}"
    
  merlin_conversation:
    enabled: true
    endpoint: "${NVIDIA_MERLIN_ENDPOINT}"
    api_key: "${NVIDIA_MERLIN_API_KEY}"

# Avatar Configuration
avatar:
  default_avatar: "professional_consultant"
  available_avatars:
    - id: "professional_consultant"
      name: "Professional Eyewear Consultant"
      description: "Expert in eyewear recommendations and face analysis"
      model_id: "nvidia_avatar_v2_professional"
      voice_profile: "professional_female"
      personality: "helpful_expert"
      
    - id: "friendly_assistant"
      name: "Friendly Shopping Assistant"
      description: "Casual and approachable eyewear helper"
      model_id: "nvidia_avatar_v2_casual"
      voice_profile: "friendly_male"
      personality: "casual_helpful"
      
  rendering:
    quality: "high"
    resolution: "1920x1080"
    frame_rate: 30
    background: "studio_neutral"
    
  animation:
    facial_expressions: true
    lip_sync: true
    gesture_tracking: true
    emotion_mapping: true

# Face Analysis Configuration
face_analysis:
  enabled: true
  provider: "mediapipe"
  confidence_threshold: 0.8
  
  features:
    face_shape: true
    facial_landmarks: true
    skin_tone: true
    eye_measurements: true
    nose_measurements: true
    
  privacy:
    store_images: false
    anonymize_data: true
    retention_period: "24h"

# Product Catalog
products:
  data_source: "demo/sample-data/demo-products.json"
  categories:
    - "prescription_glasses"
    - "sunglasses"
    - "reading_glasses"
    - "safety_glasses"
    - "blue_light_glasses"
    
  filters:
    - "frame_shape"
    - "frame_material"
    - "lens_type"
    - "brand"
    - "price_range"
    - "color"

# Conversation Configuration
conversation:
  max_session_duration: 1800  # 30 minutes
  idle_timeout: 300  # 5 minutes
  max_messages_per_session: 100
  
  features:
    voice_input: true
    voice_output: true
    text_input: true
    text_output: true
    image_analysis: true
    product_recommendations: true
    
  languages:
    - code: "en-US"
      name: "English (US)"
      default: true
    - code: "en-GB"
      name: "English (UK)"
    - code: "es-ES"
      name: "Spanish"
    - code: "fr-FR"
      name: "French"

# Security Configuration
security:
  api_rate_limiting:
    enabled: true
    requests_per_minute: 60
    burst_limit: 10
    
  input_validation:
    enabled: true
    max_message_length: 1000
    sanitize_html: true
    
  data_protection:
    encrypt_sessions: true
    secure_cookies: true
    https_only: true

# Monitoring and Analytics
monitoring:
  enabled: true
  metrics:
    - "session_duration"
    - "message_count"
    - "api_response_times"
    - "error_rates"
    - "user_satisfaction"
    
  logging:
    level: "info"
    include_user_data: false
    retention_days: 7

# Fallback Configuration
fallback:
  enabled: true
  mock_services:
    enabled: "${DEMO_FALLBACK_ENABLED}"
    avatar_service: "demo/mock-services/nvidia-mock-server.js"
    
  offline_mode:
    enabled: true
    static_responses: true
    cached_avatars: true

# Demo Scenarios
scenarios:
  - id: "first_time_user"
    name: "First Time User Experience"
    description: "New user trying virtual try-on for the first time"
    duration: 300
    steps:
      - "welcome_greeting"
      - "face_analysis_explanation"
      - "virtual_try_on_demo"
      - "recommendation_showcase"
      - "purchase_guidance"
      
  - id: "returning_customer"
    name: "Returning Customer"
    description: "Customer with previous preferences"
    duration: 180
    steps:
      - "personalized_greeting"
      - "preference_recall"
      - "new_recommendations"
      - "comparison_tool"
      
  - id: "technical_demo"
    name: "Technical Demonstration"
    description: "Showcase of AI capabilities"
    duration: 600
    steps:
      - "ai_introduction"
      - "face_analysis_deep_dive"
      - "recommendation_algorithm_explanation"
      - "avatar_technology_showcase"
      - "integration_possibilities"

# Performance Configuration
performance:
  caching:
    enabled: true
    avatar_cache_duration: 3600  # 1 hour
    product_cache_duration: 1800  # 30 minutes
    
  optimization:
    lazy_loading: true
    image_compression: true
    cdn_enabled: true
    
  limits:
    max_concurrent_sessions: 50
    max_avatar_render_time: 5000  # 5 seconds
    max_api_timeout: 10000  # 10 seconds

# Integration Settings
integrations:
  ecommerce_platforms:
    shopify:
      enabled: true
      webhook_url: "${SHOPIFY_WEBHOOK_URL}"
      
    woocommerce:
      enabled: true
      api_endpoint: "${WOOCOMMERCE_API_ENDPOINT}"
      
    magento:
      enabled: true
      api_endpoint: "${MAGENTO_API_ENDPOINT}"
      
  analytics:
    google_analytics:
      enabled: true
      tracking_id: "${GA_TRACKING_ID}"
      
    custom_analytics:
      enabled: true
      endpoint: "${ANALYTICS_ENDPOINT}"

# Development and Testing
development:
  debug_mode: "${DEMO_DEBUG_MODE}"
  verbose_logging: "${DEMO_VERBOSE_LOGGING}"
  
  testing:
    mock_api_responses: false
    simulate_delays: false
    error_simulation: false
    
  features:
    hot_reload: true
    dev_tools: true
    performance_profiling: true