# Cloud Run Service Configuration with Google Cloud Secret Manager Integration
# VARAi Commerce Studio - Security Remediation

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: varai-commerce-studio
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: "100"
        run.googleapis.com/cpu-throttling: "false"
    spec:
      serviceAccountName: varai-commerce-studio@PROJECT_ID.iam.gserviceaccount.com
      containers:
      - image: gcr.io/PROJECT_ID/varai-commerce-studio:latest
        ports:
        - containerPort: 8080
        env:
        # Stripe Configuration - Retrieved from Google Cloud Secret Manager
        - name: STRIPE_PUBLISHABLE_KEY
          valueFrom:
            secretKeyRef:
              name: stripe-publishable-key
              key: latest
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: stripe-secret-key
              key: latest
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: stripe-webhook-secret
              key: latest
        
        # Stripe Product IDs
        - name: STRIPE_STARTER_PRODUCT_ID
          valueFrom:
            secretKeyRef:
              name: stripe-starter-product-id
              key: latest
        - name: STRIPE_STARTER_PRICE_ID
          valueFrom:
            secretKeyRef:
              name: stripe-starter-price-id
              key: latest
        - name: STRIPE_PROFESSIONAL_PRODUCT_ID
          valueFrom:
            secretKeyRef:
              name: stripe-professional-product-id
              key: latest
        - name: STRIPE_PROFESSIONAL_PRICE_ID
          valueFrom:
            secretKeyRef:
              name: stripe-professional-price-id
              key: latest
        - name: STRIPE_ENTERPRISE_PRODUCT_ID
          valueFrom:
            secretKeyRef:
              name: stripe-enterprise-product-id
              key: latest
        - name: STRIPE_ENTERPRISE_PRICE_ID
          valueFrom:
            secretKeyRef:
              name: stripe-enterprise-price-id
              key: latest
        
        # Token Package Price IDs
        - name: STRIPE_TOKENS_1K_PRICE_ID
          valueFrom:
            secretKeyRef:
              name: stripe-tokens-1k-price-id
              key: latest
        - name: STRIPE_TOKENS_5K_PRICE_ID
          valueFrom:
            secretKeyRef:
              name: stripe-tokens-5k-price-id
              key: latest
        - name: STRIPE_TOKENS_10K_PRICE_ID
          valueFrom:
            secretKeyRef:
              name: stripe-tokens-10k-price-id
              key: latest
        
        # Database Configuration
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-url
              key: latest
        
        # JWT Secret
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: latest
        
        # Email Configuration
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: smtp-host
              key: latest
        - name: SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: smtp-port
              key: latest
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: smtp-user
              key: latest
        - name: SMTP_PASS
          valueFrom:
            secretKeyRef:
              name: smtp-pass
              key: latest
        - name: FROM_EMAIL
          valueFrom:
            secretKeyRef:
              name: from-email
              key: latest
        
        # Non-sensitive environment variables
        - name: NODE_ENV
          value: "production"
        - name: API_BASE_URL
          value: "https://commerce-studio-website-ddtojwjn7a-uc.a.run.app"
        - name: WEBHOOK_URL
          value: "https://commerce-studio-website-ddtojwjn7a-uc.a.run.app/api/stripe/webhook"
        
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5