# Security Policies and Configuration for AI Avatar Chat System

# JWT (JSON Web Token) Configuration
jwt:
  secret: "your-super-secret-key-that-is-at-least-32-characters-long" # Replace with env variable in production
  issuer: "com.example.aiavatar"
  audience: "com.example.aiavatar"
  access_token_expires_in: "15m"
  refresh_token_expires_in: "7d"
  algorithm: "HS256"

# OAuth 2.0 Configuration (Example with Google)
oauth2:
  providers:
    google:
      client_id: "your-google-client-id" # Replace with env variable
      client_secret: "your-google-client-secret" # Replace with env variable
      redirect_uri: "https://api.example.com/v1/auth/google/callback"
      scopes:
        - "profile"
        - "email"

# Multi-Factor Authentication (MFA)
mfa:
  enabled: true
  methods:
    - "totp" # Time-based One-Time Password
    - "sms"
  totp_issuer: "AI Avatar Chat"

# Password Policy
password_policy:
  min_length: 12
  require_uppercase: true
  require_lowercase: true
  require_numbers: true
  require_symbols: true
  prevent_reuse_count: 5

# Role-Based Access Control (RBAC)
rbac:
  roles:
    - name: "admin"
      permissions: ["*:*"]
    - name: "user"
      permissions:
        - "avatar:chat"
        - "user:profile:read"
        - "user:profile:update"
        - "data:export"
    - name: "guest"
      permissions:
        - "avatar:chat:public"

# Encryption Configuration
encryption:
  algorithm: "aes-256-gcm"
  key_rotation_days: 90
  # Key should be managed via a KMS in production

# Data Privacy and Compliance (GDPR/CCPA)
data_privacy:
  retention_policy_days: 365
  anonymization_salt: "a-very-secret-salt-for-anonymization" # Replace with env variable
  gdpr_contact: "dpo@example.com"

# Security Monitoring and Logging
security_monitoring:
  log_level: "info" # (debug, info, warn, error, fatal)
  real_time_alerting:
    enabled: true
    provider: "webhook" # (e.g., slack, pagerduty, webhook)
    webhook_url: "https://hooks.slack.com/services/..." # Replace with env variable
  anomaly_detection:
    enabled: true
    sensitivity: "medium" # (low, medium, high)

# API Security
api_security:
  rate_limiting:
    window_ms: 60000 # 1 minute
    max_requests: 100
  ddos_protection:
    enabled: true
    provider: "cloudflare" # or aws-shield, etc.
  cors:
    allowed_origins:
      - "https://app.example.com"
      - "http://localhost:3000"

# Input Validation
input_validation:
  max_input_length: 2048
  disallowed_characters: "<>\"'%;()&+"