# NVIDIA API Configuration for Live Demo
# This file configures the connection to NVIDIA's live AI services.
# It uses environment variables for sensitive data like API keys.

nvidia_services:
  # Omniverse Avatar Cloud Configuration
  # Provides photorealistic, real-time avatars.
  omniverse_avatar:
    # Endpoint URL for the Omniverse Avatar service.
    # The value is sourced from the NVIDIA_OMNIVERSE_AVATAR_URL environment variable.
    url: ${NVIDIA_OMNIVERSE_AVATAR_URL}
    
    # API key for authentication.
    # The value is sourced from the NVIDIA_API_KEY environment variable.
    api_key: ${NVIDIA_API_KEY}
    
    # Request timeout in milliseconds.
    timeout: ${API_REQUEST_TIMEOUT}
    
    # Avatar model and rendering settings.
    avatar_model: "digital_human_01"
    rendering_quality: "high"

  # DEPRECATED: Riva Speech AI Configuration
  # NOTE: Riva services have been deprecated due to licensing constraints.
  # Speech functionality is now handled by Google Cloud Speech services.
  # riva_speech: DEPRECATED - Use Google Cloud Speech instead
  
  # DEPRECATED: Merlin Conversational AI Configuration
  # NOTE: Merlin services have been deprecated due to licensing constraints.
  # Conversational AI is now handled by Google Dialogflow CX.
  # merlin_conversation: DEPRECATED - Use Google Dialogflow CX instead

# Security and Rate Limiting
# Defines security policies for accessing NVIDIA APIs.
security:
  # Maximum number of requests allowed per minute.
  # The value is sourced from the MAX_REQUESTS_PER_MINUTE environment variable.
  max_requests_per_minute: ${MAX_REQUESTS_PER_MINUTE}
  
  # Enables or disables SSL certificate verification.
  # Recommended to keep true in production.
  ssl_verify: true

# Fallback Configuration
# Specifies behavior when live APIs are unavailable.
fallback:
  # Enables or disables fallback to mock services.
  # The value is sourced from the ENABLE_MOCK_SERVICES_FALLBACK environment variable.
  enable_mock_services: ${ENABLE_MOCK_SERVICES_FALLBACK}
  
  # URL for the mock service endpoint.
  # The value is sourced from the MOCK_SERVER_URL environment variable.
  mock_server_url: ${MOCK_SERVER_URL}