name: Staging Deployment

on:
  push:
    branches: [ feature/staging-deployment-infrastructure ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      working-directory: terraform/environments/staging
      run: terraform init

    - name: Terraform Plan
      working-directory: terraform/environments/staging
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/feature/staging-deployment-infrastructure'
      working-directory: terraform/environments/staging
      run: terraform apply -auto-approve

    - name: Deploy to Cloud Run
      run: |
        echo "Staging deployment completed"
        echo "Admin Panel: https://admin-staging.varai.ai"
        echo "Documentation: https://admin-staging.varai.ai/documentation.html"